package com.dbd.cms.model.base;

import com.dbd.cms.core.DBDModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleRes<M extends BaseRoleRes<M>> extends DBDModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setRoleId(java.lang.Integer roleId) {
		set("roleId", roleId);
	}

	public java.lang.Integer getRoleId() {
		return get("roleId");
	}

	public void setResId(java.lang.Integer resId) {
		set("resId", resId);
	}

	public java.lang.Integer getResId() {
		return get("resId");
	}



}
