package com.dbd.cms.model.base;

import com.dbd.cms.core.DBDModel;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOnceLog<M extends BaseOnceLog<M>> extends DBDModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCAt(java.util.Date cAt) {
		set("c_at", cAt);
	}

	public java.util.Date getCAt() {
		return get("c_at");
	}

	public void setLAt(java.util.Date lAt) {
		set("l_at", lAt);
	}

	public java.util.Date getLAt() {
		return get("l_at");
	}

	public void setDAt(java.util.Date dAt) {
		set("d_at", dAt);
	}

	public java.util.Date getDAt() {
		return get("d_at");
	}

	public void setOperName(String operName) {
		set("operName", operName);
	}

	public String getOperName() {
		return get("operName");
	}

	public void setResult(String result) {
		set("result", result);
	}

	public String getResult() {
		return get("result");
	}

	public void setCode(String code) {
		set("code", code);
	}

	public String getCode() {
		return get("code");
	}

}
