package com.dbd.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupplierCatalog<M extends BaseSupplierCatalog<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setSupplierId(Integer supplierId) {
		set("supplierId", supplierId);
	}

	public Integer getSupplierId() {
		return get("supplierId");
	}

	public void setTaxonomyId(Integer taxonomyId) {
		set("taxonomyId", taxonomyId);
	}

	public Integer getTaxonomyId() {
		return get("taxonomyId");
	}

}
