package com.dbd.cms.model.base;

import com.dbd.cms.core.DBDModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActionLog<M extends BaseActionLog<M>> extends DBDModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setAction(String action) {
		set("action", action);
	}

	public String getAction() {
		return get("action");
	}

	public void setIp(String ip) {
		set("ip", ip);
	}

	public String getIp() {
		return get("ip");
	}

	public void setActAt(java.util.Date actAt) {
		set("act_at", actAt);
	}

	public java.util.Date getActAt() {
		return get("act_at");
	}

	public void setResult(String result) {
		set("result", result);
	}

	public String getResult() {
		return get("result");
	}

	public void setData(String data) {
		set("data", data);
	}

	public String getData() {
		return get("data");
	}

	public void setUserId(Long userId) {
		set("userId", userId);
	}

	public Long getUserId() {
		return get("userId");
	}

	public void setLoginname(String loginname) {
		set("loginname", loginname);
	}

	public String getLoginname() {
		return get("loginname");
	}

}
