package com.dbd.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupplier<M extends BaseSupplier<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setTel(String tel) {
		set("tel", tel);
	}

	public String getTel() {
		return get("tel");
	}

	public void setAddress(String address) {
		set("address", address);
	}

	public String getAddress() {
		return get("address");
	}

	public void setType(String type) {
		set("type", type);
	}

	public String getType() {
		return get("type");
	}

	public void setCompensate(String compensate) {
		set("compensate", compensate);
	}

	public String getCompensate() {
		return get("compensate");
	}

	public void setAuth(String auth) {
		set("auth", auth);
	}

	public String getAuth() {
		return get("auth");
	}

	public void setCAt(java.util.Date cAt) {
		set("c_at", cAt);
	}

	public java.util.Date getCAt() {
		return get("c_at");
	}

	public void setMAt(java.util.Date mAt) {
		set("m_at", mAt);
	}

	public java.util.Date getMAt() {
		return get("m_at");
	}

	public void setDAt(java.util.Date dAt) {
		set("d_at", dAt);
	}

	public java.util.Date getDAt() {
		return get("d_at");
	}

	public void setUserId(Integer userId) {
		set("userId", userId);
	}

	public Integer getUserId() {
		return get("userId");
	}

	public void setOrderSupport(String orderSupport) {
		set("order_support", orderSupport);
	}

	public String getOrderSupport() {
		return get("order_support");
	}

	public void setSheng(String sheng) {
		set("sheng", sheng);
	}

	public String getSheng() {
		return get("sheng");
	}

	public void setShi(String shi) {
		set("shi", shi);
	}

	public String getShi() {
		return get("shi");
	}

	public void setQu(String qu) {
		set("qu", qu);
	}

	public String getQu() {
		return get("qu");
	}

	public void setLng(java.math.BigDecimal lng) {
		set("lng", lng);
	}

	public java.math.BigDecimal getLng() {
		return get("lng");
	}

	public void setLat(java.math.BigDecimal lat) {
		set("lat", lat);
	}

	public java.math.BigDecimal getLat() {
		return get("lat");
	}

	public void setWeChat(String weChat) {
		set("weChat", weChat);
	}

	public String getWeChat() {
		return get("weChat");
	}

	public void setRate(java.math.BigDecimal rate) {
		set("rate", rate);
	}

	public java.math.BigDecimal getRate() {
		return get("rate");
	}

	public void setSummary(String summary) {
		set("summary", summary);
	}

	public String getSummary() {
		return get("summary");
	}

	public void setState(String state) {
		set("state", state);
	}

	public String getState() {
		return get("state");
	}

	public void setText(String text) {
		set("text", text);
	}

	public String getText() {
		return get("text");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return get("remark");
	}

	public void setSource(String source) {
		set("source", source);
	}

	public String getSource() {
		return get("source");
	}

	public void setIsTop(Integer isTop) {
		set("isTop", isTop);
	}

	public Integer getIsTop() {
		return get("isTop");
	}

	public void setQRCodePic(String QRCodePic) {
		set("QRCodePic", QRCodePic);
	}

	public String getQRCodePic() {
		return get("QRCodePic");
	}

	public void setLaudCount(Integer laudCount) {
		set("laud_count", laudCount);
	}

	public Integer getLaudCount() {
		return get("laud_count");
	}

	public void setCollectCount(Integer collectCount) {
		set("collect_count", collectCount);
	}

	public Integer getCollectCount() {
		return get("collect_count");
	}

}
