package com.dbd.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePriLetter<M extends BasePriLetter<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setFromUserId(Integer fromUserId) {
		set("fromUserId", fromUserId);
	}

	public Integer getFromUserId() {
		return get("fromUserId");
	}

	public void setToUserId(Integer toUserId) {
		set("toUserId", toUserId);
	}

	public Integer getToUserId() {
		return get("toUserId");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}

	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setDAt(java.util.Date dAt) {
		set("dAt", dAt);
	}

	public java.util.Date getDAt() {
		return get("dAt");
	}

}
