package com.dbd.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReadCount<M extends BaseReadCount<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setModule(String module) {
		set("module", module);
	}

	public String getModule() {
		return get("module");
	}

	public void setCId(Integer cId) {
		set("cId", cId);
	}

	public Integer getCId() {
		return get("cId");
	}

	public void setCount(Integer count) {
		set("count", count);
	}

	public Integer getCount() {
		return get("count");
	}

}
