package com.dbd.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePriLetterRecord<M extends BasePriLetterRecord<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setSplId(Integer splId) {
		set("splId", splId);
	}

	public Integer getSplId() {
		return get("splId");
	}

	public void setTxt(String txt) {
		set("txt", txt);
	}

	public String getTxt() {
		return get("txt");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}

	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setDAt(java.util.Date dAt) {
		set("dAt", dAt);
	}

	public java.util.Date getDAt() {
		return get("dAt");
	}

	public void setSenderId(Integer senderId){
		set("senderId",senderId);
	}

	public Integer getSenderId(){
		return get("senderId");
	}
	public void setReceiverId(Integer receiverId){
		set("receiverId",receiverId);
	}

	public Integer getReceiverId(){
		return get("receiverId");
	}


}
