package com.dbd.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFollow<M extends BaseFollow<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setFromUserId(Integer fromUserId) {
		set("fromUserId", fromUserId);
	}

	public Integer getFromUserId() {
		return get("fromUserId");
	}

	public void setFollowUserId(Integer followUserId) {
		set("followUserId", followUserId);
	}

	public Integer getFollowUserId() {
		return get("followUserId");
	}

}
