package com.dbd.cms.model.base;

import com.dbd.cms.core.DBDModel;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMapping<M extends BaseMapping<M>> extends DBDModel<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setContentId(java.math.BigInteger contentId) {
		set("content_id", contentId);
	}

	public java.math.BigInteger getContentId() {
		return get("content_id");
	}

	public void setTaxonomyId(java.math.BigInteger taxonomyId) {
		set("taxonomy_id", taxonomyId);
	}

	public java.math.BigInteger getTaxonomyId() {
		return get("taxonomy_id");
	}

}
