package com.dbd.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderdetail<M extends BaseOrderdetail<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setOrderinfoId(Integer orderinfoId) {
		set("orderinfoId", orderinfoId);
	}

	public Integer getOrderinfoId() {
		return get("orderinfoId");
	}

	public void setCatalogName(String catalogName) {
		set("catalogName", catalogName);
	}

	public String getCatalogName() {
		return get("catalogName");
	}

	public void setZhName(String zhName) {
		set("zhName", zhName);
	}

	public String getZhName() {
		return get("zhName");
	}

	public void setSize(String size) {
		set("size", size);
	}

	public String getSize() {
		return get("size");
	}

	public void setScientificName(String scientificName) {
		set("scientificName", scientificName);
	}

	public String getScientificName() {
		return get("scientificName");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setKbId(Integer kbId) {
		set("kbId", kbId);
	}

	public Integer getKbId() {
		return get("kbId");
	}

	public void setCAt(java.util.Date cAt) {
		set("c_at", cAt);
	}

	public java.util.Date getCAt() {
		return get("c_at");
	}

	public void setMAt(java.util.Date mAt) {
		set("m_at", mAt);
	}

	public java.util.Date getMAt() {
		return get("m_at");
	}

	public void setDAt(java.util.Date dAt) {
		set("d_at", dAt);
	}

	public java.util.Date getDAt() {
		return get("d_at");
	}

	public void setKbFit(java.math.BigDecimal kbFit) {
		set("kbFit", kbFit);
	}

	public java.math.BigDecimal getKbFit() {
		return get("kbFit");
	}

	public void setStrain(java.lang.String strain) {
		set("strain", strain);
	}

	public java.lang.String getStrain() {
		return get("strain");
	}
}
