package com.dbd.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHabitat<M extends BaseHabitat<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setFId(Integer fId) {
		set("fId", fId);
	}

	public Integer getFId() {
		return get("fId");
	}

	public void setPId(Integer pId) {
		set("pId", pId);
	}

	public Integer getPId() {
		return get("pId");
	}

}
