package com.dbd.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAt<M extends BaseAt<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setFromUserId(Integer fromUserId) {
		set("fromUserId", fromUserId);
	}

	public Integer getFromUserId() {
		return get("fromUserId");
	}

	public void setToUserId(Integer toUserId) {
		set("toUserId", toUserId);
	}

	public Integer getToUserId() {
		return get("toUserId");
	}

	public void setText(String text) {
		set("text", text);
	}

	public String getText() {
		return get("text");
	}

	public void setCAt(java.util.Date cAt) {
		set("c_at", cAt);
	}

	public java.util.Date getCAt() {
		return get("c_at");
	}

	public void setDAt(java.util.Date dAt) {
		set("d_at", dAt);
	}

	public java.util.Date getDAt() {
		return get("d_at");
	}

	public void setContentId(Integer contentId) {
		set("contentId", contentId);
	}

	public Integer getContentId() {
		return get("contentId");
	}

	public void setCommentId(Integer commentId) {
		set("commentId", commentId);
	}

	public Integer getCommentId() {
		return get("commentId");
	}

	public void setContentModule(String contentModule) {
		set("contentModule", contentModule);
	}

	public String getContentModule() {
		return get("contentModule");
	}

}
