package com.dbd.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInviteCode<M extends BaseInviteCode<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCode(String code) {
		set("code", code);
	}

	public String getCode() {
		return get("code");
	}

	public void setCAt(java.util.Date cAt) {
		set("c_at", cAt);
	}

	public java.util.Date getCAt() {
		return get("c_at");
	}

	public void setUserId(Integer userId) {
		set("userId", userId);
	}

	public Integer getUserId() {
		return get("userId");
	}

	public void setState(String state) {
		set("state", state);
	}

	public String getState() {
		return get("state");
	}

	public void setUUserid(Integer uUserid) {
		set("u_userId", uUserid);
	}

	public Integer getUUserid() {
		return get("u_userId");
	}

	public void setUAt(java.util.Date uAt) {
		set("u_at", uAt);
	}

	public java.util.Date getUAt() {
		return get("u_at");
	}

}
