package com.dbd.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCollect<M extends BaseCollect<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setUserId(Integer userId) {
		set("userId", userId);
	}

	public Integer getUserId() {
		return get("userId");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return get("title");
	}

	public void setUrl(String url) {
		set("url", url);
	}

	public String getUrl() {
		return get("url");
	}

	public void setCId(Integer cId) {
		set("cId", cId);
	}

	public Integer getCId() {
		return get("cId");
	}

	public void setModule(String module) {
		set("module", module);
	}

	public String getModule() {
		return get("module");
	}

}
