package com.dbd.cms.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("c_attachment", "id", Attachment.class);
		arp.addMapping("c_comment", "id", Comment.class);
		arp.addMapping("c_content", "id", Content.class);
		arp.addMapping("c_mapping", "id", Mapping.class);
		arp.addMapping("c_metadata", "id", Metadata.class);
		arp.addMapping("c_taxonomy", "id", Taxonomy.class);
		arp.addMapping("s_action_log", "id", ActionLog.class);
		arp.addMapping("s_notification", "id", Notification.class);
		arp.addMapping("s_param", "id", Param.class);
		arp.addMapping("s_res", "id", Res.class);
		arp.addMapping("s_role", "id", Role.class);
		arp.addMapping("s_role_res", "id", RoleRes.class);
		arp.addMapping("s_user", "id", User.class);
		arp.addMapping("s_user_role", "id", UserRole.class);
		arp.addMapping("f_area", "id", Area.class);
		arp.addMapping("f_habitat", "id", Habitat.class);
		arp.addMapping("f_knowledgebase", "id", Knowledgebase.class);
		arp.addMapping("f_supplier","id",Supplier.class);
		arp.addMapping("f_supplier_catalog","id",SupplierCatalog.class);
		arp.addMapping("f_supplier_ordertype","id",SupplierOrdertype.class);
		arp.addMapping("f_supplier_pics","id",SupplierPics.class);
		arp.addMapping("f_orderinfo","id",Orderinfo.class);
		arp.addMapping("f_orderdetail","id",Orderdetail.class);
		arp.addMapping("s_invite_code","id",InviteCode.class);
		arp.addMapping("s_at","id",At.class);
		arp.addMapping("s_mgc","id",Mgc.class);
		arp.addMapping("s_pri_letter", "id", PriLetter.class);
		arp.addMapping("s_pri_letter_record", "id", PriLetterRecord.class);
		arp.addMapping("s_laud", "id", Laud.class);
		arp.addMapping("s_collect", "id", Collect.class);
		arp.addMapping("s_follow", "id", Follow.class);
		arp.addMapping("s_read_count", "id", ReadCount.class);
		arp.addMapping("f_pic", "id", Pic.class);
	}
}

