package com.dbd.cms.model;

import com.dbd.cms.model.base.BaseActionLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActionLog extends BaseActionLog<ActionLog> {


	public static final ActionLog dao = new ActionLog();
}
