package com.dbd.cms.model;

import com.dbd.cms.Consts;
import com.dbd.cms.model.base.BaseArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Area extends BaseArea<Area> {
	public static final Area dao = new Area();

	public String getOwnerTxt(){
		Consts.LAKE_NAME[] ln=Consts.LAKE_NAME.values();
		for(Consts.LAKE_NAME e:ln){
			if(getOwner()!=null&&getOwner().equals(e.getVal())){
				return e.getValTxt();
			}
		}
		return "";
	}
}
