package com.dbd.cms.model;

import com.dbd.cms.kits.DateKit;
import com.dbd.cms.model.base.BaseAt;
import com.jfinal.kit.StrKit;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class At extends BaseAt<At> {
	public static final At dao = new At().dao();

	private Object c;
	private User fromUser;
	private String cAtTxt;

//	public Object getC(){
//		Integer kbId=getContentId().intValue();
//		if(getContentModule().equals("knowledge"))
//			c= Knowledgebase.dao.findById(kbId);
//		else if(getContentModule().equals("article"))
//			c= Content.dao.findById(kbId);
//		else if(getContentModule().equals("supplierView"))
//			c= Supplier.dao.findById(kbId);
//		return c;
//	}

	public void delByContentId(Integer cId){
		String sql="select * from s_at where commentId=?";
		List<At> list=dao.find(sql,cId);
		At at=null;
		for (int i = 0; i < list.size(); i++) {
			at=list.get(i);
			at.delete();
		}
	}

//	public User getFromUser(){
//		fromUser=User.dao.findFirstByCache(Consts.CACHE_NAMES.user.name(),new BigInteger(getFromUserId().toString()),"select * from s_user where status='0' and id=? ",new BigInteger(getFromUserId().toString()));
//		return fromUser;
//	}

	public String getFromUser_nickname(){
		return get("fromUser_nickname");
	}
	public String getFromUser_avatar(){
		return get("fromUser_avatar");
	}
	public String getContent_thumbnail(){
		return StrKit.isBlank(getStr("content_thumbnail"))?"":getStr("content_thumbnail");
	}
	public String getContent_title(){
		return StrKit.isBlank(getStr("content_title"))?"":getStr("content_title");
	}
	public String getContent_summary(){
		return StrKit.isBlank(getStr("content_summary"))?"":getStr("content_summary");
	}

	public String getCAtTxt(){
		return DateKit.dateToStr(getCAt(),DateKit.STR_DATEFORMATE);
	}

}
