package com.dbd.cms.model;

import com.dbd.cms.kits.DateKit;
import com.dbd.cms.model.base.BaseComment;
import com.jfinal.kit.StrKit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Comment extends BaseComment<Comment> {
	public static final Comment dao = new Comment();

	private User user;
//	private Object c;
//
//	public Object getC(){
//		Integer kbId=getContentId().intValue();
//		if(getContentModule().equals("kb"))
//			this.c= Knowledgebase.dao.findById(kbId);
//		else if(getContentModule().equals("article"))
//			this.c= Content.dao.findById(kbId);
//		else if(getContentModule().equals("si"))
//			this.c= Supplier.dao.findById(kbId);
//		return c;
//	}
//
//
//	public User getUser() {
//		user=User.dao.findFirstByCache(Consts.CACHE_NAMES.user.name(),getUserId(),"select * from s_user where status='0' and id=? ",getUserId());
//		return user;
//	}

	public String getUser_nickname(){
		return get("user_nickname");
	}
	public String getUser_avatar(){
		return get("user_avatar");
	}
	public String getContent_thumbnail(){
		return StrKit.isBlank(getStr("content_thumbnail"))?"":getStr("content_thumbnail");
	}
	public String getContent_title(){
		return StrKit.isBlank(getStr("content_title"))?"":getStr("content_title");
	}
	public String getContent_summary(){
		return StrKit.isBlank(getStr("content_summary"))?"":getStr("content_summary");
	}

	public String getCreatedTxt(){
		return DateKit.dateToStr(getCreated(),DateKit.STR_DATEFORMATE);
	}
}
