package com.dbd.cms.model;

import com.dbd.cms.model.base.BaseFollow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Follow extends BaseFollow<Follow> {
	public static final Follow dao = new Follow().dao();

	public User getFollowUser(){
		return User.dao.findById(getFollowUserId());
	}

}
