package com.dbd.cms.model;

import com.dbd.cms.Consts;
import com.dbd.cms.model.base.BaseHabitat;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Habitat extends BaseHabitat<Habitat> {
	public static final Habitat dao = new Habitat();

	public void delByFId(Integer fId){
		List<Habitat> list=dao.find("select * from f_habitat where fId=?",fId);
		for(Habitat habitat:list){
			habitat.delete();
		}
	}

	public String getTxt(){
		Param param=Param.dao.findFirstByCache(Consts.CACHE_NAMES.paramCache.name(),"habitat-"+getPId(),"select * from s_param where id=?",getPId());
		return (param!=null)?param.getVal():"";
	}

}
