package com.dbd.cms.model;

import com.dbd.cms.kits.DateKit;
import com.dbd.cms.model.base.BaseInviteCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InviteCode extends BaseInviteCode<InviteCode> {
	public static final InviteCode dao = new InviteCode().dao();

	public String getInviter(){
		User user=User.dao.findById(getUserId());
		return user.getNickname();
	}

	public String getSubscriber(){
		if(getUUserid()!=null) {
			User user = User.dao.findById(getUUserid());
			return user.getNickname();
		}
		else{
			return null;
		}
	}

	public String getStateTxt(){
		return (getState().equals("00"))?"未用":"已用";
	}

	public String getCatTxt(){
		return DateKit.dateToStr(getCAt(),DateKit.STR_DATEFORMATE);
	}
	public String getUatTxt(){
		return (getUAt()!=null)?DateKit.dateToStr(getUAt(),DateKit.STR_DATEFORMATE):null;
	}

}
