package com.dbd.cms.model;

import com.dbd.cms.model.base.BaseMgc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mgc extends BaseMgc<Mgc> {
	public static final Mgc dao = new Mgc().dao();
}
