package com.dbd.cms.model;

import com.dbd.cms.Consts;
import com.dbd.cms.kits.DateKit;
import com.dbd.cms.model.base.BaseNotification;

import java.math.BigInteger;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Notification extends BaseNotification<Notification> {
	public static final Notification dao = new Notification().dao();

	private User fromUser;
	private User toUser;

	private Notification reNotification;
	private Notification originalNotification;


	public User getFromUser() {

		fromUser=User.dao.findFirstByCache(Consts.CACHE_NAMES.user.name(),new BigInteger(getFromUserId().toString()),"select * from s_user where status='0' and id=? ",new BigInteger(getFromUserId().toString()));
		return fromUser;
	}

	public User getToUser() {
		toUser=User.dao.findFirstByCache(Consts.CACHE_NAMES.user.name(),new BigInteger(getFromUserId().toString()),"select * from s_user where status='0' and id=? ",new BigInteger(getFromUserId().toString()));
		return toUser;
	}

	public String getCAtTxt(){
		return DateKit.dateToStr(getCAt(),DateKit.STR_DATEFORMATE);
	}

	public Notification getReNotification() {
		if(getRId()!=null)
		reNotification=Notification.dao.findFirstByCache(Consts.CACHE_NAMES.notification.name(),"getReNotification"+getRId(),"select * from s_notification where id=?",getRId());
		return reNotification;
	}

	public Notification getOriginalNotification() {
		originalNotification=Notification.dao.findFirstByCache(Consts.CACHE_NAMES.notification.name(),"getOriginalNotification"+getRId(),"select * from s_notification where rId=?",getRId());
		return originalNotification;
	}
}
