package com.dbd.cms.model;

import com.dbd.cms.model.base.BaseOnceLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OnceLog extends BaseOnceLog<OnceLog> {
	public static final OnceLog dao = new OnceLog();
}
