package com.dbd.cms.model;

import com.dbd.cms.Consts;
import com.dbd.cms.model.base.BaseOrderinfo;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Orderinfo extends BaseOrderinfo<Orderinfo> {
	public static final Orderinfo dao = new Orderinfo().dao();

	public List<Orderinfo> findByName(String name){
		return Orderinfo.dao.findByCache(Consts.CACHE_NAMES.orderinfo.name(),"findByName"+name,"select * from f_orderinfo where name=?",name);
	}

	public List<Orderinfo> findOrderDateByZhNameAndYear(String zhName,String year){
		return Orderinfo.dao.findByCache(Consts.CACHE_NAMES.orderinfo.name(),"findOrderDateByZhNameAndYear"+year+zhName,"select id, orderDate from f_orderinfo where zhName = ? and year( orderDate  ) = year('"+year+"')  order by orderDate desc",zhName);
	}

	public List<Orderinfo> findOrderYearByZhNameLike(String zhName){
		return Orderinfo.dao.findByCache(Consts.CACHE_NAMES.orderinfo.name(),"findOrderDateByZhNameLike"+zhName,"select id, DATE_FORMAT(orderDate, '%Y') as year from f_orderinfo where zhName = ? GROUP BY DATE_FORMAT(orderDate, '%Y') order by orderDate desc",zhName);
	}

	public List<Orderinfo> findNew(int limit){
		String sql="select * from f_orderinfo where d_at is null order by c_at desc limit ?";
		return dao.findByCache(Consts.CACHE_NAMES.orderinfo.name(),"findNew"+limit,sql,limit);
	}

}
