package com.dbd.cms.model;

import com.dbd.cms.Consts;
import com.dbd.cms.model.base.BasePic;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.ehcache.CacheKit;
import com.qiniu.util.UrlSafeBase64;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Pic extends BasePic<Pic> {
	public static final Pic dao = new Pic().dao();

	/**
	 * 查询模块下某内容 用户已经上传图片数量
	 * @param userId
	 * @param module
	 * @param moduleId
	 * @return
	 */
	public long findCountByUserKey(Integer userId,String module,String moduleId){
		String sql="select count(id) from f_pic where uploadUser=? and module=? and moduleId=? and d_at is null";
		return Db.queryLong(sql,userId,module,moduleId);
	}

	public String getUserNickname(){
		return getStr("userNickname");
	}

	public String getWaterMarkParam(){
		String siteName= CacheKit.get(Consts.CACHE_NAMES.paramCache.name(),"siteName");
		String waterMarkTxt= StrKit.isBlank(getUserNickname())?siteName:siteName+"-"+getUserNickname();
		waterMarkTxt= UrlSafeBase64.encodeToString(waterMarkTxt);
		String pfops= "watermark/2/text/"+waterMarkTxt+"/font/5b6u6L2v6ZuF6buR/fontsize/360/fill/I0Y2RjRGNA==/dissolve/77/gravity/SouthEast/dx/10/dy/10";
		return pfops;
	}

}
