package com.dbd.cms.model;

import com.dbd.cms.Consts;
import com.dbd.cms.kits.DateKit;
import com.dbd.cms.model.base.BasePriLetterRecord;

import java.math.BigInteger;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PriLetterRecord extends BasePriLetterRecord<PriLetterRecord> {
	public static final PriLetterRecord dao = new PriLetterRecord().dao();
	private PriLetter priLetter;

//	public PriLetter getPriLetter() {
//		priLetter=PriLetter.dao.findById(getSplId());
//		return priLetter;
//	}

	public String getCAtTxt(){
		if(getCAt()!=null){
			return DateKit.dateToStr(getCAt(),DateKit.STR_DATEFORMATE);
		}else
			return "";
	}

	public User getSender(){
		return User.dao.findFirstByCache(Consts.CACHE_NAMES.user.name(),new BigInteger(getSenderId().toString()),"select * from s_user where status='0' and id=? ",new BigInteger(getSenderId().toString()));
	}

	public User getReceiver(){
		return User.dao.findFirstByCache(Consts.CACHE_NAMES.user.name(),new BigInteger(getReceiverId().toString()),"select * from s_user where status='0' and id=? ",new BigInteger(getReceiverId().toString()));
	}
}
