package com.dbd.cms.model;

import com.dbd.cms.model.base.BaseReadCount;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReadCount extends BaseReadCount<ReadCount> {
	public static final ReadCount dao = new ReadCount().dao();

	public ReadCount findByCIdAndModule(int cId,String module){
		return ReadCount.dao.findFirst("select * from s_read_count where cId=? and module=?",cId,module);
	}

	public void countAddOne(int cId,String module){
		String sql="update s_read_count set count=count+1 where cId=? and module=?";
		Db.update(sql,cId,module);
	}

}
