package com.dbd.cms.model;

import com.dbd.cms.Consts;
import com.dbd.cms.model.base.BaseRole;

import java.math.BigInteger;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();

	public List<Role> findRolesByUserId(BigInteger userId){
			return dao.findByCache(Consts.CACHE_NAMES.userRoles.name(),userId,"select r.* from s_role r left join s_user_role ur on r.id=ur.rid where ur.uid=?",userId );
	}

}
