package com.dbd.cms.model;

import com.dbd.cms.model.base.BaseSupplierPics;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierPics extends BaseSupplierPics<SupplierPics> {
	public static final SupplierPics dao = new SupplierPics().dao();

	public void delBySupplierId(Integer supplierId){
		List<SupplierPics> list=dao.find("select * from f_supplier_pics where supplierId=?",supplierId);
		SupplierPics sp=null;
		for (int i = 0; i < list.size(); i++) {
			sp=list.get(i);
			sp.delete();
		}
	}

}
